**05-03-2026**

**numpy**
its a numerical python

In [4]:
#there are max 64 dimensions for array
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.ndim)
#ndim used get the dimension of array

2


In [6]:
arr1=np.array([1,2,3,4])
print(arr1+2)
print(arr1*2)

[3 4 5 6]
[2 4 6 8]


In [8]:
a1=np.array([10,20,30,40])
print(a1+2,a1-2,a1*2,a1/2)

[12 22 32 42] [ 8 18 28 38] [20 40 60 80] [ 5. 10. 15. 20.]


In [21]:
a0=np.array(10)
a1=np.array([])
#zeros and ones function
z1=np.zeros(5)
o1=np.ones(5)
print(a0.ndim,a1.ndim)
print(z1,o1)

0 1
[0. 0. 0. 0. 0.] [1. 1. 1. 1. 1.]


In [19]:
ar=np.arange(1,5)
print(ar)

[1 2 3 4]


In [22]:
arr=np.array([1,2,3,4])
print(np.sum(arr))

10


In [24]:
arr=np.array([10,20,25,38,45])
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))

27.6
45
10


In [28]:
#shape to check no, of rows and columns
ar=np.zeros([1]*3)
print(ar.ndim)
print(ar.shape)

3
(1, 1, 1)


In [33]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[0:,1:])

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]


In [40]:
#concatenate()
n1=np.array([10,20,30,40])
n2=np.array([50,60,70,80])
c=np.concatenate([n1,n2])
print(c)

[10 20 30 40 50 60 70 80]


In [41]:
#where()
a=np.array([1,2,3,4,5,6,7,8])
print(np.where(a==5))

(array([4]),)


**Pandas**
it wil provide us an output in a tabular format